import React from 'react';
//Components
import Navbar from '../navbar/Navbar';
import { Sections, Wrapper,Content } from './Philosophy.styles';

const Philosophy = () => {
    return ( 
        <>
            <Navbar />
            <Wrapper>
            <h1>My Teaching Philosophy</h1>
                <Content>
                    <Sections>
                        <h2>Teaching Purpose</h2>
                        <p>When I was in elementary school, in my 5th year of studying, I had my first foreign language, and it was English. I thought I would never make it right, and I would never learn it. But, the professor was so great with a positive attitude, so interesting and she gained my attention and made me like this subject, so it becomes my favorite subject in school. She motivated me, and after some time I become good at it. During high school and faculty, I was attending English classes, but all of that professors weren't the same as my elementary school teacher, they don't care about students, they don't have passion. They had been teaching that subject and doing that job only because of money, not because they love it.</p>
                        <p>So I was thinking and thinking, so I started to do private classes for people who needed help, and volunteering. That's why I'm teaching English now and trying my best to make my students love English, make them so good at it. That’s why teaching means to me a lot because I want to help other people who also have the passion to learn new languages, but they are struggling to do so because of bad methods or teachers. I believe all people in this world can learn any language, the only thing that they need to have to a start is a good teacher, who will guide them well, and motivate them in a good way.</p>
                        <p>My short-term teaching purpose is to teach beginners, the first step is to explain the basics so they can move on, discover by themselves, and take the journey alone if they want. It’s all about the beginning, basic knowledge is very important, to be well taught after it, it’s very easy to improve more and more. Then, the fun has just started.</p>
                        <p>My long-term teaching purpose is to inspire students to reach their dreams, to be good in English, fluent, so they can travel, talk with confidence, working, meeting new people, or maybe also love of their life. The most important thing is what has been learned in classrooms, to be used in real situations, and help them in real life. That would mean to me a lot, and that means I’ve done perfect work and I will be happy for them.</p>
                    </Sections>
                    <Sections>
                        <h2>Teaching Style</h2>
                        <p>Approaches that are the most relatable to me and the way I teach are the Communicative Approach, the Affective Humanistic Approach, and the Comprehension Approach. These approaches appeal to me more than others because I’m teaching zero-level students (elementary school, beginners) I found it helpful. Zero-level students need to learn all four skills writing, speaking, listening, and reading. It’s basic, and it's part of the Communicative Approach, as well as the connection between people, different cultures, places, etc.</p>
                        <p>Also, as zero-level students, they don’t have any knowledge, and it’s hard to start, students are afraid of mistakes, so their feelings are really important. So based on the Affective Humanistic Approach, where are feelings of students essential, to let students mistakes, and tell also how I’d done a lot of mistakes, during my studies, and how that is all normal. Removing barriers to language learning, and making students comfortable in the learning environment, and I’m applying it because only in that way students will feel well and be interested to learn the language, and in the end, we are humans. The Comprehension Approach is based on making the meaning clear and helping learners gain confidence so they are willing to produce language.</p>
                        <p>Learning vocabulary through stories, music, pictures, games, costumes, which is amazing, because this is one of the best ways to get close to my students, make them interested in learning the language, without pressure. Classroom objects, visual aids, observable actions, carefully leveled books with high-interest themes, also books that contain all four skills: reading, writing, speaking, and listening. All of this I’ve found very helpful during my lessons.</p>
                        <p>What best meet the needs of my students and motivate them to learn is games, dramatization, music, singing what can help them to be so good in all of it. The best way to motivate my students is to make that kind of material, what they like and are interested in, to gain their attention, and make every class memorable for them. Important is to make them feel they are important and they can learn without pressure. With some games, all students in the class will be active, do group work, role-play. Activities like it are interesting for them. Also, some dramatizations, or even singing, all depends are shy or not, are they afraid or not, to show what they have learned. So, there is a lot of ways how to make them feel good and to have fun. Memorable classes, and to learn a lot of stuff, what are basics, so they can start their journey about learning the English language because if I teach them good and all meaning is clear, at first, my students will be able to continue learning English and become good at it.</p>
                    </Sections>
                    <Sections>
                        <h2>Teaching techniques</h2>
                        <p>Techniques I am using are: choosing a new identity, positive reinforcement, games, singing, dancing. It’s good for the human brain when studying something new to feel, smell, and hear it. In that way, my students will remember better all of what they have studied better. Also, I’m using role reversal, role-plays, authentic materials, and some activities that create opportunities to communicate in the target language. One of my favorites is “language games,” which I find very helpful, my students memorizing vocabulary easier with it. Role-plays are also a great way, and I’m using them after each unit. Also, I like role reversal, I’ve been using it for Children’s week and students enjoyed it. In some regular classes, the good technique, I'm using, is the use of simple questions and dialogues.</p>
                        <p>Gain students' attention, and motivate them every class is really important for me. As I mentioned before, I am teaching zero-level students most of the time, beginners (elementary school) so TPR, scaffolding, and 20/80 are techniques that I use always.</p>
                        <p>Whenever I'm starting a class I take about 5 minutes on warm-up, to see how are my students, are they fine, to see if they didn’t understand something, to see if all is clear, also repeating from the previous lesson then we are moving on the next lesson. Sometimes happens that no one understands anything, so I have to back and try to make things clear.</p>
                        <p>The classroom for my students looks fresh, with a lot of shapes, objects, pictures. Also, flashcards, props, etc, can help me explain to my students as well as I can. During class, we are passing some lessons, later a little bit reading, or we are listening depends on the lesson plan, so after it, we are doing practice. Most of the time that is pair work, group work, role-play, etc. When we have done some practice I can see which students understand and which are not understand some stuff. And trying to make everything clear till the end of class. Most of the time I'm giving students short quizzes but without grading, just some small rewards, so I can motivate them more and more. Five minutes before the end of the class, one student comes in front of my desk and chose one card. Like 10 students, 10 cards, and on every card, there is one English music. So before class ends, we are listening to some song. And I've noticed that students like it, and enjoying in it What I am always saying and doing, is to let students feel to make mistakes, to feel comfortable with any mistake.</p>
                        <p>Most of the time in my class, I’m explaining for 10 minutes, the other 25 minutes that have left, are for practicing. With guided practice, I want to be sure that my students can practice and produce what they have learned in that class. That can be answering individual, pairs work, or group work depends on the lesson theme. Use of independent practice like multiple-choice, true-false, matching.</p>
                        <p>Also, what I like is to give homework to my students, because they are most of the time children, so they will practice also at home, and when they come next class, we will read homework, and see what is not clear, or if all is clear, we would move on another lesson. But also, during some practices, what I’ve mentioned earlier, I can see how my students understand all from the lesson. All of this is part of the formative assessment. Not everything has to be graded.</p>
                        <p>When is time for an exam, I am sure, that my students have good knowledge and they understand all. As a part of the summative assessment, I give my students a graded final exam.</p>
                    </Sections>
                </Content>
            </Wrapper>
        </>
     );
}
 
export default Philosophy;